# Generated by Django 4.2.6 on 2023-12-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='Key',
            field=models.CharField(default=12345678, max_length=200),
            preserve_default=False,
        ),
    ]
